config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games, except: [:destroy, :edit, :update]
  get '/leaderboard', to: 'leaderboard#index'
  get '/history', to: 'games#index'
  root to: "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player_one, class_name: 'User', foreign_key: 'player_one_id'
  belongs_to :player_two, class_name: 'User', foreign_key: 'player_two_id'

  validates :player_one_score,
    numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 21
  }, presence: true

  validates :player_two_score,
    numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 21
  }, presence: true

  validate :valid_point_lead_for_win

  def rating_one
    rating_for_player(
      result: game_result,
      old_rating: player_one.rating,
      opponent_rating: player_two.rating,
      k_factor: player_one.k_factor
    )
  end

  def rating_two
    rating_for_player(
      result: (1.0 - game_result),
      old_rating: player_two.rating,
      opponent_rating: player_one.rating,
      k_factor: player_two.k_factor
    )
  end

  # Based on Elo Rating System... thanks to all those hours playing Destiny I
  # alredy knew about this one.
  #
  # http://en.wikipedia.org/wiki/Elo_rating_system#Mathematical_details
  def rating_for_player(result: nil, old_rating: 1000,
                        opponent_rating: 1000, k_factor: 32)
    (old_rating.to_f + (k_factor.to_f * (
        result.to_f - expected_rating(
          opponent_rating, old_rating
        )
      )).to_i
    )
  end

  # Based on Elo Rating System... thanks to all those hours playing Destiny I
  # alredy knew about this one.
  #
  # http://en.wikipedia.org/wiki/Elo_rating_system#Mathematical_details
  def expected_rating(other, old)
    1.0 / ( 1.0 + ( 10.0 ** ((other.to_f - old.to_f) / 400.0) ) )
  end


  def game_result
    if player_one_score > player_two_score
      1.0
    elsif player_one_score == player_two_score
      0.5
    else
      0
    end
  end

  private

  # TODO: Intent should be clear on this one. probable a less convuluted way
  # to do this exists
  def valid_point_lead_for_win
    return unless self.player_one_score && self.player_two_score
    scores = [self.player_one_score, self.player_two_score].sort
    difference = scores[1] - scores[0]
    if difference < 2 && difference > 0
      errors.add(:base, "Point difference should be of at least two points")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :games_as_player_one, class_name: 'Game',
    foreign_key: 'player_one_id'
  has_many :games_as_player_two, class_name: 'Game',
    foreign_key: 'player_two_id'


  def games
    Game.where('player_one_id = ? OR player_two_id = ?', self.id, self.id)
  end

  def k_factor
    # TODO: Naive way to do player tiers
    # Probably I would use something similar to the competitive Skill Ratings
    # of Overwatch. But since I have some time constraints and this is only a
    # toy implementation I would skip that and just take the number of games
    # as the source of the K-Factor.
    # Either way, the provided example doesn't take into account the
    # K-Factor and the effect that has on providing a more stable system and
    # ranking the users to their skill level.
    case games.count
    when 0...10
      32
    when 11...24
      24
    else
      16
    end
  end

  def update_rating!(new_rating)
    self.previous_rating = self.rating
    self.rating = new_rating
    self.save
  end

  def games_played
    games.count
  end

  def opponents
    User.where.not(id: self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  def index
    @games = current_user.games
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    @game.player_one_id = current_user.id

    if @game.save
      # TODO: Player rating recalculation: Not sure if this the right place for
      # this. Somehow it feels wrong having it here.
      update_ratings_for_players(@game)

      redirect_to games_url, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:played_on, :player_two_id,
                                   :player_one_score, :player_two_score)
    end

    def update_ratings_for_players(game)
      game.player_one.update_rating!(game.rating_one)
      game.player_two.update_rating!(game.rating_two)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
  end

  def log
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def index
    @users = User.all.order(rating: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def win_lose_draw(user, game)
    if user.id == game.player_one_id
      player_score = game.player_one_score
      opponent_score = game.player_two_score
    else
      player_score = game.player_two_score
      opponent_score = game.player_one_score
    end

    if player_score > opponent_score
      "W"
    elsif player_score < opponent_score
      "L"
    else
      "D"
    end
  end

  def opponent(user, game)
    if user.id == game.player_one_id
      game.player_two.email
    else
      game.player_one.email
    end
  end
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <div class="form-group">
    <% if game.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

        <ul>
          <% game.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :played_on, "Dated Played" %>
      <%= f.date_select :played_on %>
    </div>

    <div class="field">
      <%= f.label :player_two, "Opponent" %>
      <%= f.collection_select :player_two_id, current_user.opponents, :id, :email %>
    </div>

    <div class="field">
      <%= f.label :player_one_score, "Your Score" %>
      <%= f.number_field :player_one_score %>
    </div>

    <div class="field">
      <%= f.label :player_two_score, "Their Score" %>
      <%= f.number_field :player_two_score %>
    </div>

    <div class="actions">
      <%= f.submit "Save" %>
    </div>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date played</th>
      <th>Opponent</th>
      <th>Score</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.played_on %></td>
        <td><%= opponent(current_user, game) %></td>
        <td><%= game.player_one_score %>-<%= game.player_two_score %></td>
        <td><%= win_lose_draw(current_user, game) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date played:</strong>
  <%= @game.played_on %>
</p>

<p>
  <strong>Player one:</strong>
  <%= @game.player_one.email %>
</p>

<p>
  <strong>Player two:</strong>
  <%= @game.player_two.email %>
</p>

<p>
  <strong>Player one score:</strong>
  <%= @game.player_one_score %>
</p>

<p>
  <strong>Player two score:</strong>
  <%= @game.player_two_score %>
</p>

<%= link_to 'Back', games_path %>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_game_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leaderboard', leaderboard_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to 'History', games_path %> </li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/leaderboard/index.html.erb
<h1 class='page-header'>Leaderboard</h1>
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Rank</th>
      <th>Email</th>
      <th>Score</th>
      <th>Games Played</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= user.email %></td>
        <td><%= user.rating %></td>
        <td><%= user.games_played %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>